site_name: GynTree Documentation
site_description: Directory tree analysis and visualization tool
repo_url: https://github.com/dsj7419/gyntree
repo_name: GynTree

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - FAQ: getting-started/faq.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Configuration: user-guide/configuration.md
  - API Reference: api/overview.md
  - Contributing: contributing/guidelines.md
  - Changelog: changelog.md
