name: Documentation

on:
  push:
    paths:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
      - "requirements-docs.txt"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
      - "requirements-docs.txt"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Check documentation
        run: |
          python scripts/check_docs.py

      - name: Build documentation
        run: |
          mkdocs build --strict --verbose
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload documentation artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site
          retention-days: 14
