name: Documentation

on:
  push:
    paths:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
      - "requirements-docs.txt"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
      - "requirements-docs.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Check documentation links
        run: |
          mkdocs build --strict

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          commit_message: |
            Deploy documentation updates

            Triggered by ${{ github.sha }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          full_commit_message: |
            Deploy documentation updates

            Triggered by ${{ github.sha }}
            Commit messages:
            ${{ github.event.commits[0].message }}
